### ISSUE TITLE
Uptime 0.1 Cacti 1.2.12 errors upon install

### ISSUE THREAD

**Issue by bmfmancini** [xmacan/plugin_uptime#2]
Hey Petr,

i see the following errors when enabling uptime plugin the plugin seems to work though

2020/06/15 13:16:03 - ERROR PHP NOTICE in Plugin 'uptime': Undefined offset: 1600 in file: /var/www/html/cacti/plugins/uptime/setup.php on line: 117
2020/06/15 13:16:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[816]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:uptime_poller_bottom(), /plugins/uptime/setup.php[117]:CactiErrorHandler())
2020/06/15 13:16:03 - ERROR PHP NOTICE in Plugin 'uptime': Undefined offset: 1597 in file: /var/www/html/cacti/plugins/uptime/setup.php on line: 117

**Comment by xmacan** [comment]
ups ... I missed this post, I will look at it

**Comment by xmacan** [comment]
During the install? It is strange, there was error but it can occurs when is uptime is running (in poller). Please try it now. If you want keep your data, comment line in setup.php:
db_execute("DROP TABLE `plugin_uptime_data`");

Please let me know ...
